### ISSUE TITLE
Extra characters when printing in Pluto.jl

### ISSUE THREAD

**Issue by chenspc** [Roger-luo/Configurations.jl#18]
I was trying to using `Configurations.jl` in `Pluto.jl`. When making an option type object, the printing shows extract characters. Not sure if this is an issue more suitable here or in `Pluto.jl`..
<img width="957" alt="extra_characters" src="https://user-images.githubusercontent.com/10161227/110398635-232e6b00-806c-11eb-860b-e68c88d9cc70.png">

**Comment by Roger-luo** [comment]
haha, this is because Pluto doesn't support ASCII color characters - would be nice if Pluto supports it. I'm not sure what's the right way to disable it, it's probably a question for Pluto.

**Comment by Roger-luo** [comment]
@fonsp I'm wondering if there is a way to let the default HTML printing fallback to Pluto?

I guess we can assume that Configurations.jl would replace the previous option types defined manually inside Pluto, so some special handling based on `is_option` method is possible.

**Comment by fonsp** [comment]
I'll look into this!

**Comment by Roger-luo** [comment]
@fonsp I found a solution to this: https://juliadocs.github.io/ANSIColoredPrinters.jl/dev/

this allows me to replace the ASCII color escape characters with HTML class, but then I will need to use some CSS to visualize it for Pluto. Wondering what would be the best HTML output for Pluto?
or should I use a different MIME type other than `text/html`

**Comment by Roger-luo** [comment]
current since Pluto doesn't have a CSS definition of ASCII types, you would get the following with this method

![image](https://user-images.githubusercontent.com/8445510/113775942-5f023200-96f7-11eb-94d6-a204cdf1ae6b.png)

but I still prefers the default Pluto visualization...
