### ISSUE TITLE
[FR] `from_flat_kwargs` like in Pluto

### ISSUE THREAD

**Issue by fonsp** [Roger-luo/Configurations.jl#26]
In Pluto, you implemented `from_flat_kwargs`, which allowed syntax like:

```julia
@option struct A
	x
end

@option struct B
	a::A
end

from_flat_kwargs(B, x=1)
```

I like it! Can it be added to Configuration.jl as well?

**Comment by fonsp** [comment]
Original source code ise here https://github.com/fonsp/Pluto.jl/blob/48705944814350fece494710aceffba83cc987e4/src/Configuration.jl#L135-L176

**Comment by Roger-luo** [comment]
yeah I think this is the same as `from_kwargs` function here?

**Comment by fonsp** [comment]
Sorry for the vague example! To clarify: in Configurations.jl, the last line of my example is:
```julia
from_kwargs(B, a_x=1)
```
because I need to specify the prefix `a_`. In Pluto, these are detected "automatically":
```julia
from_flat_kwargs(B, x=1)
```

**Comment by fonsp** [comment]
## Context

I would like to use Configurations.jl in Pluto.jl, but the prefix means that old keyword arguments won't work anymore, because `Pluto.run(threads=123)` becomes `Pluto.run(compiler_threads=123)`.

## Ambiguity

I think that `from_flat_kwargs` should error if any two subfields have the same name, i.e. if an ambiguity is possible, even if the given kwargs are not ambiguous. That way, the package creator will know in time that their configurtion cannot be set using `from_flat_kwargs`.

**Comment by Roger-luo** [comment]
I see, so the difference between `from_kwargs` and `from_flat_kwargs` is:

1. `from_kwargs` use `_` to disambiguate subfields of the same name
2. `from_flat_kwargs` errors when there are subfields of the same name

correct?
