### ISSUE TITLE
Overriding configurations in a conf file from the command line

### ISSUE THREAD

**Issue by rejuvyesh** [Roger-luo/Configurations.jl#7]
Not sure if this should go to `Comonicon.jl` instead but say I want to be able to override some specific variable in the config from the command line using say an argument to `--set`. 

An example:

```
julia cmd.jl path/to/conf.toml 
```

can be transformed with:

```
julia cmd.jl path/to/conf.toml --set seed=42
```

What would be the best way to merge these configuration options?
Thanks for such a useful library.

**Comment by Roger-luo** [comment]
You should implement your own CLI and forward the kwargs to `from_toml` or `from_dict`'s kwargs, e.g

```julia
@cast function foo(filename; seed=45)
    from_toml(filename; seed=45)
end
```

**Comment by rejuvyesh** [comment]
I see. Thanks. But this wouldn't work for arbitrary nested config options. Like say:

```
julia cmd.jl path/to/conf.toml --set phase1.opt.name="ADAM"
```
Would the following make sense:
```
@cast function foo(filename; kwargs...)
from_toml(filename; kwargs...)
end
```

**Comment by Roger-luo** [comment]
I think you are referring to https://github.com/Roger-luo/Comonicon.jl/issues/89 let's move the discussion there - It sounds like a useful feature but I don't have time to implement it recently, would be nice if someone is willing to implement it.
